### ISSUE TITLE
Service crashes on launch: "One or more errors occurred. (One or more errors occurred. (Could not parse player times, check logs!))"

### ISSUE THREAD

**Issue by michaave** [crowbarmaster/BedrockManagementService#106]
When I try to open BedrockService.Service.exe I get the following: 

"Configuration Result:
[Success] Name BedrockService
[Success] Description Windows Service Wrapper for Windows Bedrock Server
[Success] ServiceName BedrockService
Topshelf v4.3.0.0, .NET 6.0.26 (6.0.26)
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Minecraft Server (BMS)
Service: Starting service...
Service: Loaded Service props.
Service: You must agree to the terms set by Mojang for use of this software.
Read terms at: https://minecraft.net/terms
Type "Yes" to affirm you agree to afformentioned terms to continue:
yes
Service: Loaded config for server Lucky Block World.
Service: Exception occured Main : One or more errors occurred. (One or more errors occurred. (Could not parse player times, check logs!))
Topshelf.Hosts.ConsoleRunHost Error: 0 : An exception occurred, System.AggregateException: One or more errors occurred. (One or more errors occurred. (Could not parse player times, check logs!))
 ---> System.AggregateException: One or more errors occurred. (Could not parse player times, check logs!)
 ---> System.InvalidOperationException: Could not parse player times, check logs!
   at BedrockService.Shared.Classes.Player.UpdatePlayerFromDbStrings(String[] dbString)
   at BedrockService.Service.Management.ConfigManager.<>c__DisplayClass20_0.<LoadPlayerDatabase>b__6(String[] x) in D:\a\BedrockManagementService\BedrockManagementService\BedrockService\Service\Management\ConfigManager.cs:line 363
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at BedrockService.Service.Management.ConfigManager.LoadPlayerDatabase(IServerConfiguration server) in D:\a\BedrockManagementService\BedrockManagementService\BedrockService\Service\Management\ConfigManager.cs:line 362
   at BedrockService.Service.Management.ConfigManager.<LoadServerConfigurations>b__10_0() in D:\a\BedrockManagementService\BedrockManagementService\BedrockService\Service\Management\ConfigManager.cs:line 64
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at BedrockService.Service.Core.BedrockService.<Initialize>b__16_0() in D:\a\BedrockManagementService\BedrockManagementService\BedrockService\Service\Core\BedrockService.cs:line 63
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at BedrockService.Service.Core.BedrockService.Start(HostControl hostControl) in D:\a\BedrockManagementService\BedrockManagementService\BedrockService\Service\Core\BedrockService.cs:line 88
   at Topshelf.Builders.ControlServiceBuilder`1.ControlServiceHandle.Start(HostControl hostControl)
   at Topshelf.Hosts.ConsoleRunHost.Run()"

I check the logs, but I just get the same content, "Could not parse player times, check logs!"
Oddly enough the servers run fine if I go to the folder: C:\MCBedrockService\Lucky Block World" and run the "BedrockService.Lucky Block World.exe", the server runs fine, but I cannot use your GUI, it fails to connect with no other error than "failed to connect". It worked fine the first time it opened, but after closing and re-opening, it gives this error. Is this a bug or is there something I can clear?

**Comment by michaave** [comment]
One thing I noticed in the error is the reference to this file (that does not exist): D:\a\BedrockManagementService\BedrockManagementService\BedrockService\Service\Core\BedrockService.cs

**Comment by michaave** [comment]
Anyone else experiencing this error, just delete the folder: "C:\Minecraft Server (BMS)\BmsConfig\ServerConfigs\PlayerRecords", they will be recreated by the service executable on launch, and will allow you to use the frontend again.

**Comment by crowbarmaster** [comment]
Hello and welcome! Please give the latest beta a go. This will soon be marked as the stable as that version is well out of date now. Please, let me know how it goes!

**Comment by michaave** [comment]
I'm sorry I didn't respond, your new beta works great
